# Generated by Django 2.1 on 2018-08-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('flight_name', models.CharField(max_length=20)),
                ('dept_time', models.CharField(max_length=10)),
                ('arrival_time', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
    ]
